/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package vista;


/**
 *
 * @author copad
 */
import java.sql.ResultSet;
import java.sql.Statement;
import negocio.CRUDS.CRUD_Desarrolladora;
import negocio.Conexion.Conexion;
import negocio.Entidades.EntidadDesarrolladora;
public class Desarrolladora extends javax.swing.JDialog {

    /**
     * Creates new form desarrolladora
     */
    public Desarrolladora() {
        
        initComponents();
        jLabelAnuncio.setVisible(false);
        rellenarComboBox();
    }
        public void rellenarComboBox(){
        Conexion conexion=new Conexion();
        Statement statement;
        ResultSet resulset;
        jComboBoxID.removeAllItems();
        try {
            statement=conexion.getConexionBaseDatos().createStatement();
            resulset=statement.executeQuery("SELECT * FROM desarrolladora");
            jComboBoxID.addItem("Nuevo elemento");
            while(resulset.next()){
               jComboBoxID.addItem(resulset.getInt("id")+" "+resulset.getString("nombre")); 
            }
        } catch (Exception e) {
            System.out.println("error"+" "+e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxID = new javax.swing.JComboBox();
        jTextNombre = new javax.swing.JTextField();
        jLabelAnuncio = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombre.setText("nombre");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jComboBoxID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIDActionPerformed(evt);
            }
        });

        jLabelAnuncio.setText("se incerto el dato");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(Guardar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(nombre))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jComboBoxID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextNombre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelAnuncio)
                        .addGap(94, 94, 94)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabelAnuncio)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        EntidadDesarrolladora desarrolladora=new EntidadDesarrolladora(0,jTextNombre.getText() );
        CRUD_Desarrolladora crud=new CRUD_Desarrolladora();
        boolean incertoDato=crud.incertar(desarrolladora);
        
        if(incertoDato=true){
            jLabelAnuncio.setVisible(true);
        }else{
            jLabelAnuncio.setText("ocurrio un error");
            jLabelAnuncio.setVisible(true);
        }
        rellenarComboBox();
        jTextNombre.setText("");
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String cadena=jComboBoxID.getSelectedItem().toString();
        String[] separarnumero=cadena.split(" ");
        int numero=Integer.parseInt(separarnumero[0]);
        
        CRUD_Desarrolladora crud=new CRUD_Desarrolladora();
        EntidadDesarrolladora eDesarrolladora=new EntidadDesarrolladora(numero, separarnumero[1]);
        
        boolean elimino=crud.eliminar(eDesarrolladora);
        
        if(elimino=true){
            jLabelAnuncio.setText("se elimino correctamente");
            jLabelAnuncio.setVisible(true);
        }
        rellenarComboBox();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cadena=jComboBoxID.getSelectedItem().toString();
        String[] separarnumero=cadena.split(" ");
        int numero=Integer.parseInt(separarnumero[0]);
        
        CRUD_Desarrolladora crud=new CRUD_Desarrolladora();
        EntidadDesarrolladora entidadDesa=new EntidadDesarrolladora(numero, jTextNombre.getText());
        
        crud.modificar(entidadDesa);
        
        rellenarComboBox();
        
        jTextNombre.setText("");
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAnuncio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
