/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.ResultSet;
import java.sql.Statement;
import negocio.CRUDS.CRUD_Videojuegos;
import negocio.Conexion.Conexion;
import negocio.Entidades.EntidadVideoJuego;

/**
 *
 * @author copad
 */
public class VideoJuego extends javax.swing.JDialog {

    /**
     * Creates new form VideoJuegos
     */
    public VideoJuego() {
        
        initComponents();
        jLabelAnuncio.setVisible(false);
        rellenarComboBoxID();
        rellenarComboBoxDesarrolladora();
    }
    
    public void rellenarComboBoxID() {
        Conexion conexion = new Conexion();
        Statement statement;
        ResultSet resulset;
        jComboBoxID.removeAllItems();
        try {
            statement = conexion.getConexionBaseDatos().createStatement();
            resulset = statement.executeQuery("SELECT * FROM videojuego");
            jComboBoxID.addItem("Nuevo elemento");
            while (resulset.next()) {
                jComboBoxID.addItem(resulset.getInt("idVideojuego") + " " + resulset.getString("nombre"));
            }
        } catch (Exception e) {
            System.out.println("error" + " " + e);
        }

    }

    public void rellenarComboBoxDesarrolladora() {
        Conexion conexion = new Conexion();
        Statement statement;
        ResultSet resulset;
        jComboBoxIDDesarrolladora.removeAllItems();
        try {
            statement = conexion.getConexionBaseDatos().createStatement();
            resulset = statement.executeQuery("SELECT * FROM desarrolladora");
            
            while (resulset.next()) {
                jComboBoxIDDesarrolladora.addItem(resulset.getInt("id") + " "+resulset.getString("nombre") );
            }
        } catch (Exception e) {
            System.out.println("error" + " " + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Guardar = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBoxID = new javax.swing.JComboBox();
        jComboBoxIDDesarrolladora = new javax.swing.JComboBox();
        jTextRating = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jLabelAnuncio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Desarrolladora");

        jLabel3.setText("Nombre");

        jLabel4.setText("Rating");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxIDDesarrolladora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxID, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxIDDesarrolladora, 0, 181, Short.MAX_VALUE)
                            .addComponent(jTextRating)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2))
                    .addComponent(jComboBoxIDDesarrolladora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabelAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        CRUD_Videojuegos crud=new CRUD_Videojuegos();
        
        String cadena=jComboBoxIDDesarrolladora.getSelectedItem().toString();
        String[] separarnumero=cadena.split(" ");
        int numeroDesarrolladora=Integer.parseInt(separarnumero[0]);
        
        int rating=Integer.parseInt(jTextRating.getText());
        EntidadVideoJuego entidad=new EntidadVideoJuego(0, jTextNombre.getText(), numeroDesarrolladora, rating);
        crud.incertar(entidad);
        
        jLabelAnuncio.setText("se gurdo correctamente");
        jLabelAnuncio.setVisible(true);
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CRUD_Videojuegos crud = new CRUD_Videojuegos();

        String cadena = jComboBoxID.getSelectedItem().toString();
        String[] separarnumero = cadena.split(" ");
        int numeroIDJuego = Integer.parseInt(separarnumero[0]);
        
        
        
        
        EntidadVideoJuego entidadVideoJuego=new EntidadVideoJuego(numeroIDJuego, "", 0, 0);
        
        crud.eliminar(entidadVideoJuego);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CRUD_Videojuegos crud = new CRUD_Videojuegos();

        String cadena = jComboBoxID.getSelectedItem().toString();
        String[] separarnumero = cadena.split(" ");
        int numeroIDJuego = Integer.parseInt(separarnumero[0]);
        
        String cadena2 = jComboBoxIDDesarrolladora.getSelectedItem().toString();
        String[] separarnumero2 = cadena2.split(" ");
        int numeroIDDesarrolladora = Integer.parseInt(separarnumero[0]);
        
        int rating=Integer.parseInt(jTextRating.getText());
        
        EntidadVideoJuego entidadVideoJuego=new EntidadVideoJuego(numeroIDJuego, jTextNombre.getText(), numeroIDDesarrolladora, rating);
        
        crud.modificar(entidadVideoJuego);
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxID;
    private javax.swing.JComboBox jComboBoxIDDesarrolladora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAnuncio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextRating;
    // End of variables declaration//GEN-END:variables
}
